use_frameworks!

target 'PMNetworking_Example' do
  pod 'PMNetworking', :path => '../'

  target 'PMNetworking_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end


target 'PMNetworking_Mac_Example' do
  pod 'PMNetworking', :path => '../'

  target 'PMNetworking_Mac_ExampleTests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
