source 'https://cdn.cocoapods.org/'
#source 'git@gitlab.protontech.ch:proton/mobile/apple/podspecs.git'


platform :ios, '10.0'

use_frameworks!

target 'PMNetworking_Example' do
  pod 'PMCrypto', :git => 'https://gitlab.protontech.ch/apple/shared/pmcrypto.git', :tag => '1.1.0'
  pod 'PMCommon', :path => '../', :testspecs => ['Tests']
#  pod 'PMAuthentication', :git => 'https://gitlab.protontech.ch/apple/shared/pmauthentication.git', :tag => '1.0.0'
  
  
  #  pod 'PMAPIClient', :path => '../', :testspecs => ['Tests']
  #  pod 'PMNetworking-Alamofire', :path => '../', :testspecs => ['Tests']
  
  target 'PMNetworking_Tests' do
    inherit! :search_paths
    #    pod 'Quick', '~> 1.2.0'
    #    pod 'Nimble', '~> 7.0'
    #    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end


target 'PMNetworking_Mac_Example' do
  pod 'PMCommon', :testspecs => ['Tests'], :path => '../'
  
  target 'PMNetworking_Mac_ExampleTests' do
    inherit! :search_paths
    #    pod 'Quick', '~> 1.2.0'
    #    pod 'Nimble', '~> 7.0'
    #    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
