stages:
  - linting
  - unit_tests

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

lint:
  stage: linting
  tags:
    - iOS
  script:
    - cd Example
    - Pods/SwiftLint/swiftlint --reporter junit > swiftlint.xml
  allow_failure: false
  artifacts:
    name: "core-lint-$CI_COMMIT_TAG"
    paths:
      - swiftlint.xml
    reports:
      junit:
        - swiftlint.xml
    expire_in: 90 days

unit_tests:
  dependencies: []
  stage: unit_tests
  script:
    - xcodebuild -workspace Example/PMNetworking.xcworkspace -scheme PMCommon-iOS-Unit-Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' test | xcpretty
  tags:
    - iOS
